version: '3.8'

services:
  yaml-generator:
    build:
      context: .
      dockerfile: Dockerfile
    image: spheronfdn/spheron-yaml-gen-api:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    restart: unless-stopped
    volumes:
      - ./templates:/app/templates
      - ./yaml:/app/yaml
