version: '3.8'

services:
  yaml-generator:
    build:
      context: .
      dockerfile: Dockerfile
    image: spheronfdn/spheron-yaml-gen-api:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    restart: unless-stopped
    volumes:
      - ./templates:/app/templates
      - ./yaml:/app/yaml
