version: "1.0"

services:
  py-cuda:
    image: spheronnetwork/jupyter-notebook:pytorch-2.4.1-cuda-enabled
    pull_policy: IfNotPresent
    expose:
      - port: 8888
        as: 8888
        to:
          - global: true
      - port: 3000
        as: 3000
        to:
          - global: true
    env:
      - JUPYTER_TOKEN=test

profiles:
  name: py-cuda
  duration: 24h
  mode: provider
  compute:
    py-cuda:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 120Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090

  placement:
    westcoast:
      attributes:
        region_exclude: china
      pricing:
        py-cuda:
          token: CST
          amount: 0.5
deployment:
  py-cuda:
    westcoast:
      profile: py-cuda
      count: 1
